# fly.toml app configuration file generated for my-mysql-hidden-rain-8326 on 2024-10-29T23:10:55-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-mysql-hidden-rain-8326'
primary_region = 'scl'

[build]
  image = 'mysql:8'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 3306
  protocol = "tcp"

[[services.ports]]
  port = 3306

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
